server:
  port: 8766

#\u670D\u52A1\u7684\u540D\u79F0
spring:
  application:
    name: zuul-gateway
  cloud:
    #    1.注册中心发现config配置
    config:
      discovery:
        enabled: true # 通过服务发现的方式去找配置中心
        service-id: config-server # 配置中心的名字，直接配置名称可以在配置中心集群的时候实现负载均衡
      name: redis,client
      profile: dev # 对应配置中心文件的${profile}部分
#\u6307\u5B9A\u6CE8\u518C\u4E2D\u5FC3\u5730\u5740
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#服务注册
  instance:
    hostname: device
    prefer-ip-address: true
#\u81EA\u5B9A\u4E49\u8DEF\u7531\u6620\u5C04
zuul:
#  prefix: /api  #前缀
  #  routes:
#    service-login: /login-service/**  #service-login：微服务注册名， login-service ：访问前缀
#  ignored-patterns: /*-service/**
  routes:
    ts:
      path: /login-service/**
      serviceId: service-login
