eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8764
spring:
  application:
    name: service-login
  cloud:
    #    1.注册中心发现config配置
    config:
      discovery:
        enabled: true # 通过服务发现的方式去找配置中心
        service-id: config-server # 配置中心的名字，直接配置名称可以在配置中心集群的时候实现负载均衡
      name: ds,ds-mybatise,redis,client
      profile: dev # 对应配置中心文件的${profile}部分
    management:
      security:
        enabled: false
    endpoints:
      refresh:
        enabled: true
